[2025-06-02T15:24:23.975+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_scraper_pipeline.processar_relevantes manual__2025-06-02T15:09:07.943661+00:00 [queued]>
[2025-06-02T15:24:23.979+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_scraper_pipeline.processar_relevantes manual__2025-06-02T15:09:07.943661+00:00 [queued]>
[2025-06-02T15:24:23.979+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-06-02T15:24:23.983+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): processar_relevantes> on 2025-06-02 15:09:07.943661+00:00
[2025-06-02T15:24:23.986+0000] {standard_task_runner.py:57} INFO - Started process 1452 to run task
[2025-06-02T15:24:23.987+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'google_scraper_pipeline', 'processar_relevantes', 'manual__2025-06-02T15:09:07.943661+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/google_scraper_dag.py', '--cfg-path', '/tmp/tmp_xtzou7v']
[2025-06-02T15:24:23.989+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask processar_relevantes
[2025-06-02T15:24:24.011+0000] {task_command.py:415} INFO - Running <TaskInstance: google_scraper_pipeline.processar_relevantes manual__2025-06-02T15:09:07.943661+00:00 [running]> on host 1457ea4f74d2
[2025-06-02T15:24:24.042+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_scraper_pipeline' AIRFLOW_CTX_TASK_ID='processar_relevantes' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T15:09:07.943661+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T15:09:07.943661+00:00'
[2025-06-02T15:24:26.794+0000] {logging_mixin.py:151} INFO - ‚úÖ Dependencies installed successfully
[2025-06-02T15:24:26.796+0000] {logging_mixin.py:151} INFO - üì¶ Executing command: python3 /opt/***/dags/google_scraper/processador/processar_relevantes.py --dias 1
[2025-06-02T15:24:27.674+0000] {logging_mixin.py:151} INFO - Return code: 1
[2025-06-02T15:24:27.674+0000] {logging_mixin.py:151} INFO - Output: 
[2025-06-02T15:24:27.674+0000] {logging_mixin.py:151} INFO - Errors: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/processador/processar_relevantes.py", line 11, in <module>
    from extracao.extractor import resolve_google_news_url, fetch_and_extract_article_text
  File "/opt/***/dags/google_scraper/extracao/extractor.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-06-02T15:24:27.674+0000] {logging_mixin.py:151} INFO - ‚ö†Ô∏è Command failed with return code 1
[2025-06-02T15:24:27.675+0000] {logging_mixin.py:151} INFO - ‚ö†Ô∏è Error executing command: Command '['python3', '/opt/***/dags/google_scraper/processador/processar_relevantes.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T15:24:27.675+0000] {logging_mixin.py:151} INFO - Output: 
[2025-06-02T15:24:27.675+0000] {logging_mixin.py:151} INFO - Error output: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/processador/processar_relevantes.py", line 11, in <module>
    from extracao.extractor import resolve_google_news_url, fetch_and_extract_article_text
  File "/opt/***/dags/google_scraper/extracao/extractor.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-06-02T15:24:27.675+0000] {logging_mixin.py:151} INFO - ‚ö†Ô∏è Error in processar_relevantes: Command '['python3', '/opt/***/dags/google_scraper/processador/processar_relevantes.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T15:24:27.675+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_scraper_dag.py", line 104, in processar_relevantes
    return run_script("processador/processar_relevantes.py", dias, date)
  File "/opt/airflow/dags/google_scraper_dag.py", line 70, in run_script
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/dags/google_scraper/processador/processar_relevantes.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T15:24:27.681+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=google_scraper_pipeline, task_id=processar_relevantes, execution_date=20250602T150907, start_date=20250602T152423, end_date=20250602T152427
[2025-06-02T15:24:27.687+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task processar_relevantes (Command '['python3', '/opt/airflow/dags/google_scraper/processador/processar_relevantes.py', '--dias', '1']' returned non-zero exit status 1.; 1452)
[2025-06-02T15:24:27.720+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-02T15:24:27.734+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
