[2025-06-02T16:45:52.833+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [queued]>
[2025-06-02T16:45:52.837+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [queued]>
[2025-06-02T16:45:52.837+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2025-06-02T16:45:52.843+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_scraper> on 2025-06-02 16:36:58.866401+00:00
[2025-06-02T16:45:52.845+0000] {standard_task_runner.py:60} INFO - Started process 654 to run task
[2025-06-02T16:45:52.847+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_scraper_pipeline', 'run_scraper', 'manual__2025-06-02T16:36:58.866401+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/google_scraper_dag.py', '--cfg-path', '/tmp/tmp8d84b5sy']
[2025-06-02T16:45:52.848+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask run_scraper
[2025-06-02T16:45:52.870+0000] {task_command.py:423} INFO - Running <TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [running]> on host ab064e19f47a
[2025-06-02T16:45:52.906+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_scraper_pipeline' AIRFLOW_CTX_TASK_ID='run_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T16:36:58.866401+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T16:36:58.866401+00:00'
[2025-06-02T16:45:53.688+0000] {logging_mixin.py:188} INFO - ‚úÖ Depend√™ncias instaladas com sucesso
[2025-06-02T16:45:53.688+0000] {logging_mixin.py:188} INFO - üì¶ A executar comando: python3 /opt/***/dags/google_scraper/scraping/run_scraper_***.py --dias 1
[2025-06-02T16:45:53.705+0000] {logging_mixin.py:188} INFO - C√≥digo de retorno: 1
[2025-06-02T16:45:53.705+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:45:53.705+0000] {logging_mixin.py:188} INFO - Erros: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper_***.py", line 14, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:45:53.705+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Comando falhou com c√≥digo de retorno 1
[2025-06-02T16:45:53.705+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro ao executar comando: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper_***.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:45:53.705+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:45:53.706+0000] {logging_mixin.py:188} INFO - Erro: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper_***.py", line 14, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:45:53.706+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro em run_scraper: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper_***.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:45:54.510+0000] {logging_mixin.py:188} INFO - ‚úÖ Depend√™ncias instaladas com sucesso
[2025-06-02T16:45:54.510+0000] {logging_mixin.py:188} INFO - üì¶ A executar comando: python3 /opt/***/dags/google_scraper/scraping/run_scraper.py --dias 1
[2025-06-02T16:45:54.529+0000] {logging_mixin.py:188} INFO - C√≥digo de retorno: 1
[2025-06-02T16:45:54.529+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:45:54.529+0000] {logging_mixin.py:188} INFO - Erros: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper.py", line 4, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:45:54.529+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Comando falhou com c√≥digo de retorno 1
[2025-06-02T16:45:54.529+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro ao executar comando: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:45:54.530+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:45:54.530+0000] {logging_mixin.py:188} INFO - Erro: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper.py", line 4, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:45:54.530+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro no fallback run_scraper: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:45:54.530+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/google_scraper_dag.py", line 107, in run_scraper
    return run_script("scraping/run_scraper_airflow.py", dias, date)
  File "/opt/airflow/dags/google_scraper_dag.py", line 88, in run_script
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/dags/google_scraper/scraping/run_scraper_airflow.py', '--dias', '1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_scraper_dag.py", line 112, in run_scraper
    return run_script("scraping/run_scraper.py", dias, date)
  File "/opt/airflow/dags/google_scraper_dag.py", line 88, in run_script
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:45:54.537+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_scraper_pipeline, task_id=run_scraper, execution_date=20250602T163658, start_date=20250602T164552, end_date=20250602T164554
[2025-06-02T16:45:54.543+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task run_scraper (Command '['python3', '/opt/airflow/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.; 654)
[2025-06-02T16:45:54.584+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-02T16:45:54.597+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
