[2025-06-02T17:10:03.266+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [queued]>
[2025-06-02T17:10:03.270+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [queued]>
[2025-06-02T17:10:03.270+0000] {taskinstance.py:2170} INFO - Starting attempt 8 of 9
[2025-06-02T17:10:03.274+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_scraper> on 2025-06-02 16:36:58.866401+00:00
[2025-06-02T17:10:03.276+0000] {standard_task_runner.py:60} INFO - Started process 1002 to run task
[2025-06-02T17:10:03.278+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_scraper_pipeline', 'run_scraper', 'manual__2025-06-02T16:36:58.866401+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/google_scraper_dag.py', '--cfg-path', '/tmp/tmpqic4iae0']
[2025-06-02T17:10:03.279+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask run_scraper
[2025-06-02T17:10:03.301+0000] {task_command.py:423} INFO - Running <TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [running]> on host 4a3ff0e975f7
[2025-06-02T17:10:03.337+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_scraper_pipeline' AIRFLOW_CTX_TASK_ID='run_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T16:36:58.866401+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T16:36:58.866401+00:00'
[2025-06-02T17:10:03.338+0000] {logging_mixin.py:188} INFO - ⚠️ Erro em run_scraper: name 'run_script' is not defined
[2025-06-02T17:10:03.338+0000] {logging_mixin.py:188} INFO - ⚠️ Erro no fallback run_scraper: name 'run_script' is not defined
[2025-06-02T17:10:03.338+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/google_scraper_dag.py", line 99, in run_scraper
    return run_script("scraping/run_scraper_airflow.py", dias, date)
           ^^^^^^^^^^
NameError: name 'run_script' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/google_scraper_dag.py", line 104, in run_scraper
    return run_script("scraping/run_scraper.py", dias, date)
           ^^^^^^^^^^
NameError: name 'run_script' is not defined
[2025-06-02T17:10:03.342+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=google_scraper_pipeline, task_id=run_scraper, execution_date=20250602T163658, start_date=20250602T171003, end_date=20250602T171003
[2025-06-02T17:10:03.347+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task run_scraper (name 'run_script' is not defined; 1002)
[2025-06-02T17:10:03.377+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-02T17:10:03.388+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
