[2025-06-02T16:43:58.993+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper scheduled__2025-06-01T00:00:00+00:00 [queued]>
[2025-06-02T16:43:59.003+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper scheduled__2025-06-01T00:00:00+00:00 [queued]>
[2025-06-02T16:43:59.003+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-02T16:43:59.013+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_scraper> on 2025-06-01 00:00:00+00:00
[2025-06-02T16:43:59.017+0000] {standard_task_runner.py:60} INFO - Started process 162 to run task
[2025-06-02T16:43:59.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_scraper_pipeline', 'run_scraper', 'scheduled__2025-06-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/google_scraper_dag.py', '--cfg-path', '/tmp/tmposkny7p1']
[2025-06-02T16:43:59.027+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask run_scraper
[2025-06-02T16:43:59.075+0000] {task_command.py:423} INFO - Running <TaskInstance: google_scraper_pipeline.run_scraper scheduled__2025-06-01T00:00:00+00:00 [running]> on host ab064e19f47a
[2025-06-02T16:43:59.175+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_scraper_pipeline' AIRFLOW_CTX_TASK_ID='run_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T00:00:00+00:00'
[2025-06-02T16:44:03.501+0000] {logging_mixin.py:188} INFO - ‚úÖ Depend√™ncias instaladas com sucesso
[2025-06-02T16:44:03.502+0000] {logging_mixin.py:188} INFO - üì¶ A executar comando: python3 /opt/***/dags/google_scraper/scraping/run_scraper_***.py --dias 1
[2025-06-02T16:44:03.534+0000] {logging_mixin.py:188} INFO - C√≥digo de retorno: 1
[2025-06-02T16:44:03.534+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:44:03.535+0000] {logging_mixin.py:188} INFO - Erros: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper_***.py", line 14, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:44:03.535+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Comando falhou com c√≥digo de retorno 1
[2025-06-02T16:44:03.535+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro ao executar comando: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper_***.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:44:03.535+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:44:03.535+0000] {logging_mixin.py:188} INFO - Erro: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper_***.py", line 14, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:44:03.535+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro em run_scraper: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper_***.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:44:04.531+0000] {logging_mixin.py:188} INFO - ‚úÖ Depend√™ncias instaladas com sucesso
[2025-06-02T16:44:04.531+0000] {logging_mixin.py:188} INFO - üì¶ A executar comando: python3 /opt/***/dags/google_scraper/scraping/run_scraper.py --dias 1
[2025-06-02T16:44:04.550+0000] {logging_mixin.py:188} INFO - C√≥digo de retorno: 1
[2025-06-02T16:44:04.550+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:44:04.551+0000] {logging_mixin.py:188} INFO - Erros: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper.py", line 4, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:44:04.551+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Comando falhou com c√≥digo de retorno 1
[2025-06-02T16:44:04.551+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro ao executar comando: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:44:04.551+0000] {logging_mixin.py:188} INFO - Resultado: 
[2025-06-02T16:44:04.551+0000] {logging_mixin.py:188} INFO - Erro: Traceback (most recent call last):
  File "/opt/***/dags/google_scraper/scraping/run_scraper.py", line 4, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
[2025-06-02T16:44:04.551+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro no fallback run_scraper: Command '['python3', '/opt/***/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:44:04.551+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/google_scraper_dag.py", line 107, in run_scraper
    return run_script("scraping/run_scraper_airflow.py", dias, date)
  File "/opt/airflow/dags/google_scraper_dag.py", line 88, in run_script
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/dags/google_scraper/scraping/run_scraper_airflow.py', '--dias', '1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/google_scraper_dag.py", line 112, in run_scraper
    return run_script("scraping/run_scraper.py", dias, date)
  File "/opt/airflow/dags/google_scraper_dag.py", line 88, in run_script
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['python3', '/opt/airflow/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.
[2025-06-02T16:44:04.558+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=google_scraper_pipeline, task_id=run_scraper, execution_date=20250601T000000, start_date=20250602T164358, end_date=20250602T164404
[2025-06-02T16:44:04.565+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task run_scraper (Command '['python3', '/opt/airflow/dags/google_scraper/scraping/run_scraper.py', '--dias', '1']' returned non-zero exit status 1.; 162)
[2025-06-02T16:44:04.584+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-02T16:44:04.596+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
